### ISSUE TITLE
Replace include macro with normal module?

### ISSUE THREAD

**Issue by julianskartor** [mapbox-jp/holidays-rs#3]

**Comment by AD4MANTIS** [comment]
Hi,
I tried out this crate for a personal project and made some changes to split up the code.
You can find the current state here:
https://github.com/AD4MANTIS/holidays-rs
One thing I want to do before creating a PR is to split the countries into their own module files. This should be everything to complete this issue. 

After that I also want to support subdivision, because they would be nice for my project. If you have already thought about how to best implement this, please let me know.
